Docs/architecture handbook
Taro-IT/Espresso_doc pull request #1
Opened 2021-11-09 13:34 UTC by sebastafoya

Agregar handbook de arquitectura

2021-11-12 13:53 UTC, JuanManuelAmador requested changes

2021-11-12 13:53 UTC, JuanManuelAmador commented on docs/handbook_arquitectura/POL05-politica-de-despliegue.md
> +<li>Informar al equipo de cualquier problema en el despliegue y una vez que se haya realizado de manera exitosa.</li>
se podria agregar -Asegurarse que el despliegue cubre una Epic o un modulo completo de funcionalidades que se pueden mostrar en una demo

2021-11-12 13:53 UTC, JuanManuelAmador commented on docs/handbook_arquitectura/configuration/configuracion-local.md
> +_Explica que verifican estas pruebas y por qué_
Esto se va a agregar despues o a que se refiere?

2021-11-16 15:23 UTC, JoseCarlosPa approved these changes

2021-11-16 16:01 UTC, JoseCarlosPa approved these changes

2021-11-16 22:29 UTC, merged